### PR TITLE
fix: pre-page & default

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
数据显示不出来那个问题也一起修了？

**Comment by atian25** [comment]
稍等, 我看看

**Comment by fengmk2** [comment]
@atian25 修完提交？

**Comment by atian25** [comment]
提交了, 合并后先不发版本吧, 我等会再发个 PR 把 detail 界面也补上

**Pull request merged**
