### PR TITLE
feat: redirect / to /news

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
我发个版本。

**Comment by fengmk2** [comment]
1.2.2

**Comment by atian25** [comment]
回头还是得把这几个 boilerplate 的单测结合 egg-init补上来, 不然都不是很放心

**Pull request merged**
